import type { Product } from "./fitverse-types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "fv-01",
    name: "Banarasi Kadhwa Silk Saree",
    brand: "Raghurai Textiles",
    city: "Varanasi",
    gender: "women",
    category: "Ethnic",
    subcategory: "Sarees",
    price: 18400,
    mrp: 24500,
    fabric: "Pure Katan silk, real zari",
    colorName: "Deep Wine & Antique Gold",
    swatch: ["#4b1027", "#c39b52"],
    sizes: ["Free"],
    rating: 4.8,
    reviews: 214,
    tryOnFee: 0,
    description:
      "Handwoven on a pit loom over 21 days, with kadhwa buta booties and a broad antique zari pallu. Comes with an unstitched blouse piece.",
  },
  {
    id: "fv-02",
    name: "Chikankari Anarkali with Dupatta",
    brand: "Awadh Atelier",
    city: "Lucknow",
    gender: "women",
    category: "Ethnic",
    subcategory: "Anarkali",
    price: 7650,
    mrp: 10900,
    fabric: "Mulmul cotton, hand chikankari",
    colorName: "Powder Ivory",
    swatch: ["#e7e0d2", "#bfae92"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 168,
    tryOnFee: 0,
    description:
      "Featherlight 52-panel Anarkali with murri and phanda hand embroidery, finished with a matching mul dupatta.",
  },
  {
    id: "fv-03",
    name: "Raw Silk Bridal Lehenga",
    brand: "Chandni Couture",
    city: "Jaipur",
    gender: "women",
    category: "Occasion",
    subcategory: "Bridal",
    price: 62500,
    mrp: 82000,
    fabric: "Raw silk with dabka & sequin work",
    colorName: "Sindoor Red",
    swatch: ["#7b1113", "#d8a53f"],
    sizes: ["S", "M", "L"],
    rating: 4.9,
    reviews: 96,
    tryOnFee: 499,
    description:
      "Nine-metre flared kalidar lehenga with hand dabka vines, a corseted blouse and a scalloped net dupatta.",
  },
  {
    id: "fv-04",
    name: "Ajrakh Block Print Kurta Set",
    brand: "Kutch Karigar",
    city: "Bhuj",
    gender: "women",
    category: "Ethnic",
    subcategory: "Kurta Sets",
    price: 3290,
    mrp: 4600,
    fabric: "Natural-dye cotton",
    colorName: "Indigo & Madder",
    swatch: ["#1f3557", "#9c4634"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviews: 341,
    tryOnFee: 0,
    description:
      "Straight kurta with matching pants, hand block printed in sixteen stages of natural dye by Ajrakhpur artisans.",
  },
  {
    id: "fv-05",
    name: "Organza Cocktail Slip Dress",
    brand: "Studio Noir Bombay",
    city: "Mumbai",
    gender: "women",
    category: "Occasion",
    subcategory: "Cocktail",
    price: 11200,
    mrp: 14000,
    fabric: "Silk organza, satin lining",
    colorName: "Champagne",
    swatch: ["#d9c49a", "#8d7a55"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    reviews: 78,
    tryOnFee: 299,
    description:
      "Bias-cut slip with a sheer organza overlay and a covered-button back. Cut for a fluid, unlined-looking drape.",
  },
  {
    id: "fv-06",
    name: "Khadi Denim Wide-Leg Jeans",
    brand: "Loom & Ledger",
    city: "Bengaluru",
    gender: "women",
    category: "Western",
    subcategory: "Denim",
    price: 2890,
    mrp: 3900,
    fabric: "13oz handspun khadi denim",
    colorName: "Raw Indigo",
    swatch: ["#26364f", "#4d6485"],
    sizes: ["26", "28", "30", "32", "34"],
    rating: 4.4,
    reviews: 512,
    tryOnFee: 0,
    description:
      "High-rise wide leg in unwashed khadi denim that fades to your own wear pattern. Selvedge outseam.",
  },
  {
    id: "fv-07",
    name: "Linen Co-ord with Shell Buttons",
    brand: "Malabar Line",
    city: "Kochi",
    gender: "women",
    category: "Western",
    subcategory: "Co-ords",
    price: 4450,
    mrp: 5900,
    fabric: "European flax linen",
    colorName: "Sandstone",
    swatch: ["#cbb79d", "#8c7a63"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 187,
    tryOnFee: 0,
    description:
      "Boxy camp-collar shirt and pleated shorts in pre-washed linen that softens with every wash.",
  },
  {
    id: "fv-08",
    name: "Kanjivaram Half-Silk Saree",
    brand: "Meenakshi Silks",
    city: "Kanchipuram",
    gender: "women",
    category: "Ethnic",
    subcategory: "Sarees",
    price: 9800,
    mrp: 13200,
    fabric: "Silk-cotton with korvai border",
    colorName: "Peacock & Mustard",
    swatch: ["#0f4a52", "#c8952c"],
    sizes: ["Free"],
    rating: 4.7,
    reviews: 233,
    tryOnFee: 0,
    description:
      "Korvai contrast border interlocked by hand, with a temple-motif rudraksha pallu. Everyday drape weight.",
  },
  {
    id: "fv-09",
    name: "Ivory Silk Sherwani with Stole",
    brand: "Hukum Bespoke",
    city: "Delhi",
    gender: "men",
    category: "Occasion",
    subcategory: "Wedding",
    price: 34500,
    mrp: 45000,
    fabric: "Dupion silk, resham & zardozi",
    colorName: "Warm Ivory",
    swatch: ["#eae2cf", "#b99b5c"],
    sizes: ["38", "40", "42", "44", "46"],
    rating: 4.8,
    reviews: 121,
    tryOnFee: 499,
    description:
      "Full-length sherwani with zardozi placement on the placket and cuffs, churidar and a tissue stole included.",
  },
  {
    id: "fv-10",
    name: "Velvet Bandhgala Jacket",
    brand: "Hukum Bespoke",
    city: "Delhi",
    gender: "men",
    category: "Ethnic",
    subcategory: "Bandhgala",
    price: 16900,
    mrp: 21500,
    fabric: "Cotton velvet, canvas front",
    colorName: "Bottle Green",
    swatch: ["#173b2c", "#c0a15b"],
    sizes: ["38", "40", "42", "44"],
    rating: 4.7,
    reviews: 88,
    tryOnFee: 299,
    description:
      "Half-canvassed bandhgala in matte velvet with a mandarin collar and gold-tone brass buttons.",
  },
  {
    id: "fv-11",
    name: "Silk Nehru Jacket",
    brand: "Peshwa & Sons",
    city: "Pune",
    gender: "men",
    category: "Ethnic",
    subcategory: "Nehru Jacket",
    price: 5400,
    mrp: 7200,
    fabric: "Matka silk",
    colorName: "Slate Blue",
    swatch: ["#2f4358", "#8fa4bb"],
    sizes: ["38", "40", "42", "44", "46"],
    rating: 4.5,
    reviews: 204,
    tryOnFee: 0,
    description:
      "Textured matka silk waistcoat with a five-button front and welt pockets, made to layer over kurtas.",
  },
  {
    id: "fv-12",
    name: "Mul Cotton Kurta & Pyjama",
    brand: "Kabir Handloom",
    city: "Kolkata",
    gender: "men",
    category: "Ethnic",
    subcategory: "Kurta Sets",
    price: 2650,
    mrp: 3400,
    fabric: "Handloom mul cotton",
    colorName: "Chalk White",
    swatch: ["#efece4", "#c2bcae"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviews: 476,
    tryOnFee: 0,
    description:
      "Breathable handloom kurta with a hand-finished placket and drawstring pyjama. Summer-wedding staple.",
  },
  {
    id: "fv-13",
    name: "Merino Travel Blazer",
    brand: "Hillside Tailors",
    city: "Chennai",
    gender: "men",
    category: "Western",
    subcategory: "Blazers",
    price: 12900,
    mrp: 16500,
    fabric: "Stretch merino wool",
    colorName: "Charcoal",
    swatch: ["#2b2e33", "#6b7076"],
    sizes: ["38", "40", "42", "44"],
    rating: 4.6,
    reviews: 143,
    tryOnFee: 299,
    description:
      "Unstructured two-button blazer in crease-recovering merino, cut for long flights and long days.",
  },
  {
    id: "fv-14",
    name: "Jamdani Weave Shirt",
    brand: "Kabir Handloom",
    city: "Kolkata",
    gender: "men",
    category: "Western",
    subcategory: "Shirts",
    price: 3150,
    mrp: 4200,
    fabric: "Handwoven jamdani cotton",
    colorName: "Ash Grey",
    swatch: ["#5c6165", "#a9aeb2"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.4,
    reviews: 261,
    tryOnFee: 0,
    description:
      "Camp-collar shirt in inlaid jamdani cotton, with a soft-fused collar and mother-of-pearl buttons.",
  },
  {
    id: "fv-15",
    name: "Kala Cotton Overshirt",
    brand: "Kutch Karigar",
    city: "Bhuj",
    gender: "unisex",
    category: "Streetwear",
    subcategory: "Overshirts",
    price: 4100,
    mrp: 5400,
    fabric: "Rain-fed kala cotton",
    colorName: "Undyed Beige",
    swatch: ["#c9bda6", "#7f7460"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviews: 158,
    tryOnFee: 0,
    description:
      "Boxy unisex overshirt in indigenous rain-fed cotton, with patch pockets and a dropped shoulder.",
  },
  {
    id: "fv-16",
    name: "Bandhani Oversized Tee",
    brand: "Chowk Studio",
    city: "Ahmedabad",
    gender: "unisex",
    category: "Streetwear",
    subcategory: "Tees",
    price: 1490,
    mrp: 1990,
    fabric: "240gsm combed cotton",
    colorName: "Ink & Saffron",
    swatch: ["#1d2233", "#d98828"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.3,
    reviews: 623,
    tryOnFee: 0,
    description:
      "Heavyweight tee tie-dyed in traditional bandhani dots, garment-washed for zero shrinkage.",
  },
  {
    id: "fv-17",
    name: "Quilted Sujani Jacket",
    brand: "Chowk Studio",
    city: "Ahmedabad",
    gender: "unisex",
    category: "Streetwear",
    subcategory: "Jackets",
    price: 6300,
    mrp: 8400,
    fabric: "Hand-quilted sujani cotton",
    colorName: "Rust & Cream",
    swatch: ["#8a4326", "#e2d3b8"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 112,
    tryOnFee: 299,
    description:
      "Reversible bomber hand-quilted in running stitch by Bihar's sujani karigars. Every piece runs unique.",
  },
  {
    id: "fv-18",
    name: "Kids Festive Kurta Set",
    brand: "Nanhe Threads",
    city: "Jaipur",
    gender: "kids",
    category: "Ethnic",
    subcategory: "Kurta Sets",
    price: 1850,
    mrp: 2500,
    fabric: "Cotton silk blend",
    colorName: "Marigold",
    swatch: ["#d99b21", "#7a4c12"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    rating: 4.5,
    reviews: 197,
    tryOnFee: 0,
    description:
      "Soft cotton-silk kurta with a printed Nehru jacket and elasticated churidar — no scratchy linings.",
  },
];
